Repository OpenSCAP/openscap, pull requests merged in 2018-08, with the labels that each got.

#1147 The function was freeing unowned memory using const pointers
  src/CVRF/cvrf_priv.c
Labels: bugfix

#1148 Do not build the documentation on every build
  docs/CMakeLists.txt
Labels: docs, enhancement

#1131 Use suffix for alpha release
  CMakeLists.txt
  libopenscap.pc.in
Labels: BLOCKER, bugfix

#1158 Fix broken SCE in master branch
  CMakeLists.txt
  config.h.in
  src/CMakeLists.txt
Labels: BLOCKER, bugfix

#1160 Travis improvements
  .travis.yml
  docs/developer/developer.adoc
Labels: enhancement, test

#1163 Remove suspicious occurences of OSCAP_API in oscap_error.h
  src/common/public/oscap_error.h
Labels: enhancement

#1159 Disable MITRE tests by default
  CMakeLists.txt
  Dockerfiles/mitre_tests
  docs/contribute/testing.adoc
  docs/developer/developer.adoc
  tests/mitre/CMakeLists.txt
Labels: enhancement, test

#1165 Fix broken compiler visibility presets
  CMakeLists.txt
  src/CPE/public/cpe_dict.h
  src/OVAL/public/oval_agent_xccdf_api.h
  src/OVAL/public/oval_definitions.h
  src/OVAL/public/oval_results.h
  src/OVAL/public/oval_system_characteristics.h
  src/common/public/oscap_text.h
  tests/API/OVAL/glob_to_regex/CMakeLists.txt
  tests/API/SEAP/CMakeLists.txt
  tests/API/crypt/CMakeLists.txt
  tests/API/probes/CMakeLists.txt
  tests/probes/xinetd/CMakeLists.txt
Labels: BLOCKER, bugfix

#1145 Remove SEXP_parser
  src/OVAL/oval_enumerations.c
  src/OVAL/probes/SEAP/_seap-types.h
  src/OVAL/probes/SEAP/_sexp-parser.h
  src/OVAL/probes/SEAP/public/sexp-parser.h
  src/OVAL/probes/SEAP/public/sexp.h
  src/OVAL/probes/SEAP/seap-descriptor.c
  src/OVAL/probes/SEAP/seap-descriptor.h
  src/OVAL/probes/SEAP/seap-packet.c
  src/OVAL/probes/SEAP/seap.c
  src/OVAL/probes/SEAP/sexp-parser.c
  src/OVAL/public/oval_definitions.h
  tests/API/SEAP/CMakeLists.txt
  tests/API/SEAP/test_api_seap.sh
  tests/API/SEAP/test_api_seap_parser.c
  tests/API/SEAP/test_api_sexp_ID.c
  tests/API/probes/fts.sh
  tests/API/probes/oval_fts_list.c
Labels: big_idea, bugfix, enhancement, test

#1168 Update OSX CI builds
  .travis.yml
Labels: enhancement

#1169 Add ENABLE_DOCS to control building documentation
  CMakeLists.txt
  docs/CMakeLists.txt
Labels: bugfix

#1174 Improve check_public_api.py script
  tests/check_public_api.py
Labels: enhancement

#1170 Made the rpm-related pkg-config configuration more robust.
  configure.ac
Labels: bugfix

#1143 Make verbose mode a common option for all modules
  src/common/debug.c
  src/common/public/oscap_debug.h
  utils/oscap-ds.c
  utils/oscap-info.c
  utils/oscap-oval.c
  utils/oscap-tool.c
  utils/oscap-vm.8
  utils/oscap-xccdf.c
  utils/oscap.8
Labels: enhancement

#1186 Developer manual: added cmake command which enables docs building
  docs/developer/developer.adoc
Labels: docs

#1187 Refactored the oscap-docker script.
  utils/oscap-docker.in
  utils/oscap_docker_python/oscap_docker_util.py
Labels: oscap-docker
