Repository OpenSCAP/openscap, pull requests merged in 2018-04, with the labels that each got.

#1010 Update "Build OpenSCAP Using Visual Studio" section in User Manual
  docs/manual/manual.adoc
Labels: docs

#1012 Fix oscap_dirname on Windows
  src/common/util.c
Labels: bugfix

#1013 Use chroot offline mode for rpm probes
  src/OVAL/probes/unix/linux/rpminfo.c
  src/OVAL/probes/unix/linux/rpmverify.c
  src/OVAL/probes/unix/linux/rpmverifyfile.c
  src/OVAL/probes/unix/linux/rpmverifypackage.c
Labels: BLOCKER, bugfix

#1019 Add wmi57 Windows probe
  CMakeLists.txt
  config.h.in
  src/CMakeLists.txt
  src/OVAL/probes/probe-table.c
  src/OVAL/probes/windows/CMakeLists.txt
  src/OVAL/probes/windows/wmi57_probe.c
  src/OVAL/probes/windows/wmi57_probe.h
Labels: enhancement
