Repository OpenSCAP/openscap, pull requests merged in 2018-03, with the labels that each got.

#990 Increased robustness of configure script regarding to Python.
  ac_probes/configure.ac.tpl
  configure.ac
Labels: bugfix

#983 Update the XCCDF HTML Guide XSLT
  xsl/xccdf-guide-impl.xsl
  xsl/xccdf-report-impl.xsl
Labels: enhancement

#994 Remove unused code in SEXP
  src/OVAL/probes/SEAP/CMakeLists.txt
  src/OVAL/probes/SEAP/_sexp-datatype.h
  src/OVAL/probes/SEAP/sexp-datatype.c
  src/OVAL/probes/SEAP/sexp-manip.c
  src/OVAL/probes/SEAP/sexp-parser.c
  src/OVAL/probes/SEAP/sexp-template.c
  src/OVAL/probes/SEAP/sexp-template.h
Labels: enhancement

#996 Don't repeatedly call getenv in SEXP_VALIDATE
  src/OVAL/probes/SEAP/sexp-manip.c
Labels: enhancement

#999 Change offline mode in system info probe to not use chroot()
  ac_probes/configure.ac.tpl
  configure.ac
  src/OVAL/probes/independent/system_info.c
  tests/Makefile.am
  tests/offline_mode/Makefile.am
  tests/offline_mode/grubenv
  tests/offline_mode/test_system_info.sh
  tests/offline_mode/textfilecontent54.oval.xml
Labels: offline scan

#1003 Avoid passing NULL parameters to oscap_seterr
  src/XCCDF/elements.h
Labels: bugfix

#1000 Improve offline mode
  src/OVAL/probes/independent/family.c
  src/OVAL/probes/independent/filehash.c
  src/OVAL/probes/independent/filehash58.c
  src/OVAL/probes/independent/filemd5.c
  src/OVAL/probes/independent/system_info.c
  src/OVAL/probes/independent/textfilecontent.c
  src/OVAL/probes/independent/textfilecontent54.c
  src/OVAL/probes/independent/variable.c
  src/OVAL/probes/independent/xmlfilecontent.c
  src/OVAL/probes/probe-skeleton.c
  src/OVAL/probes/probe/input_handler.c
  src/OVAL/probes/probe/main.c
  src/OVAL/probes/probe/offline_mode.c
  src/OVAL/probes/probe/option.h
  src/OVAL/probes/probe/probe.h
  src/OVAL/probes/probe/worker.c
  src/OVAL/probes/public/probe-api.h
  src/OVAL/probes/unix/file.c
  src/OVAL/probes/unix/fileextendedattribute.c
  src/OVAL/probes/unix/linux/partition.c
  src/OVAL/probes/unix/linux/rpminfo.c
  src/OVAL/probes/unix/linux/rpmverify.c
  src/OVAL/probes/unix/linux/rpmverifyfile.c
  src/OVAL/probes/unix/linux/rpmverifypackage.c
  src/OVAL/probes/unix/password.c
  src/OVAL/probes/unix/runlevel.c
  src/OVAL/probes/unix/shadow.c
  src/OVAL/probes/unix/symlink.c
  src/OVAL/probes/unix/xinetd.c
Labels: enhancement, offline scan

#1002 Fix offline scan in probes
  src/OVAL/probes/independent/filehash.c
  src/OVAL/probes/independent/filehash58.c
  src/OVAL/probes/independent/filemd5.c
  src/OVAL/probes/independent/textfilecontent.c
  src/OVAL/probes/independent/textfilecontent54.c
  src/OVAL/probes/independent/xmlfilecontent.c
  src/OVAL/probes/oval_fts.c
  src/OVAL/probes/oval_fts.h
  src/OVAL/probes/unix/file.c
  src/OVAL/probes/unix/fileextendedattribute.c
  src/OVAL/probes/unix/gconf.c
  src/OVAL/probes/unix/linux/selinuxsecuritycontext.c
  src/OVAL/probes/unix/sysctl.c
  src/common/util.c
  src/common/util.h
  tests/API/probes/oval_fts_list.c
  tests/offline_mode/Makefile.am
  tests/offline_mode/test_offline_mode_system_info.sh
  tests/offline_mode/test_offline_mode_textfilecontent54.sh
  tests/offline_mode/textfilecontent54.oval.xml
Labels: bugfix, offline scan
