Repository OpenSCAP/openscap, pull requests merged in 2018-07, with the labels that each got.

#1080 Update hopelessly outdated build documentation on master
  README.md
  docs/developer/developer.adoc
  docs/manual/manual.adoc
Labels: docs

#1094 Link the bindings to CPython ABI
  swig/python3/CMakeLists.txt
Labels: bugfix

#1095 Enable perl bindings if dependencies were found
  CMakeLists.txt
Labels: enhancement

#1097 Use found CMAKE ${PYTHON_EXECUTABLE} for SWIG Python3 CMakeLists.txt
  swig/python3/CMakeLists.txt
Labels: bugfix

#1096 Disable probes in SWIG
  swig/openscap.i
Labels: bugfix

#1104 Set CMAKE_BUILD_TYPE
  CMakeLists.txt
Labels: bugfix

#1107 Add _DARWIN_C_SOURCE definition for OSX
  CMakeLists.txt
Labels: bugfix

#1111 Do not include build-win32 directory in the source tarball
  CMakeLists.txt
Labels: enhancement

#1110 Fix broken file name in install command in SWIG Perl bindings
  swig/perl/CMakeLists.txt
Labels: bugfix

#1108 Move OS Defines into Config.h
  compat/oscap_platforms.h
  config.h.in
  src/OVAL/probes/independent/system_info_probe.c
  src/OVAL/probes/unix/file_probe.c
  src/OVAL/probes/unix/fileextendedattribute_probe.c
Labels: bugfix

#1113 More OSX fixes
  src/OVAL/probes/unix/fileextendedattribute_probe.c
  src/OVAL/probes/unix/password_probe.c
  src/OVAL/probes/unix/routingtable_probe.c
Labels: bugfix

#1117 Add Travis CI Badge
  README.md
Labels: enhancement

#1109 Build HTML documentation using CMake
  CMakeLists.txt
  docs/CMakeLists.txt
  docs/developer/developer.adoc
Labels: docs

#1118 fileextendedattribute_probe requires xattr header, only enable it if …
  CMakeLists.txt
  config.h.in
  docs/developer/developer.adoc
  src/OVAL/probes/unix/fileextendedattribute_probe.c
Labels: BLOCKER

#1092 Build Windows Installer in AppVeyor
  appveyor.yml
Labels: enhancement

#1120 Move dev_to_tty to compat
  CMakeLists.txt
  compat/CMakeLists.txt
  compat/compat.h
  compat/dev_to_tty.c
  config.h.in
  src/CMakeLists.txt
  src/OVAL/probes/unix/CMakeLists.txt
  src/OVAL/probes/unix/process58-devname.h
  src/OVAL/probes/unix/process58_probe.c
  src/OVAL/probes/unix/process_probe.c
Labels: BLOCKER

#1116 Prepare automated release tools for first alpha release from master branch
  CMakeLists.txt
  release_tools/release.sh
  release_tools/versions.sh
Labels: BLOCKER

#1121 Fix install commands in CMake
  dist/CMakeLists.txt
  src/SCE/CMakeLists.txt
Labels: BLOCKER

#1106 Add Windows build to the upstream release guide
  release_tools/README.adoc
Labels: docs, enhancement

#1129 Add test for filehash58 offline mode.
  tests/probes/filehash58/Makefile.am
  tests/probes/filehash58/check_filehash_simple.xml
  tests/probes/filehash58/test_probes_filehash58.sh
Labels: offline scan, test

#1075 Fix building using MINGW
  CMakeLists.txt
  src/CMakeLists.txt
  src/OVAL/probes/CMakeLists.txt
  src/XCCDF/result.c
  src/common/debug.c
Labels: bugfix

#1133 Using AsciiDoc instead of Asciidoctor to generate HTML documentation
  CMakeLists.txt
  docs/CMakeLists.txt
  docs/contribute/testing.adoc
  docs/developer/developer.adoc
  docs/manual/manual.adoc
Labels: BLOCKER

#1137 Remove 'oscap oval list-probes' submodule
  utils/oscap-oval.c
  utils/oscap.8
Labels: enhancement

#1140 Clean up implementation of strto_ functions
  src/OVAL/probes/SEAP/generic/strto.c
  src/OVAL/probes/SEAP/generic/strto.h
  src/OVAL/probes/SEAP/sexp-parser.c
  tests/API/SEAP/test_api_seap_parser.c
Labels: bugfix, test

#1128 Reduce warnings
  docs/Doxyfile.in
  docs/contribute/contribute.adoc
  docs/contribute/testing.adoc
  src/OVAL/probes/SEAP/sexp-parser.c
  src/OVAL/probes/probe-api.c
  src/XCCDF_POLICY/xccdf_policy.c
  swig/perl/CMakeLists.txt
  swig/python3/CMakeLists.txt
  tests/API/OVAL/test_api_syschar.c
  utils/oscap-info.c
  utils/oscap-tool.h
Labels: bugfix, docs, enhancement, test

#1142 Remove unused hexadecimal logic in SEXP double quote parsing
  src/OVAL/probes/SEAP/sexp-parser.c
Labels: bugfix
