Repository OpenSCAP/openscap, pull requests merged in 2018-10, with the labels that each got.

#1210 Plug memory leaks
  src/OVAL/probes/independent/textfilecontent54.c
Labels: bug

#1200 Check if CMake policy CMP0063 is defined
  CMakeLists.txt
Labels: bugfix

#1216 Fixed some Coverity issues
  src/OVAL/probes/unix/process.c
  src/SCE/sce_engine.c
  src/XCCDF_POLICY/xccdf_policy_remediate.c
Labels: bug

#1218 Coverity fixes related to oscap_...name
  src/XCCDF/xccdf_session.c
  src/common/oscap_acquire.c
Labels: bug

#1204 Fixed a memory leak, introduced Stable_free.
  src/OVAL/probes/SEAP/seap-command-backendS.c
Labels: bug

#1208 Make sure that intermediate results are freed.
  src/OVAL/probes/probe-api.c
  src/OVAL/probes/unix/linux/selinuxsecuritycontext.c
Labels: bug

#1223 Check lock return values
  src/OVAL/probes/SEAP/seap-packet.c
Labels: enhancement

#1225 Fixed missing var declaration.
  src/SCE/sce_engine.c
Labels: bug

#1230 Fix a python binding install glitch.
  swig/python3/CMakeLists.txt
Labels: bug

#1236 Fixed SWIG code in typemaps that was not freeing memory.
  swig/src/openscap.i
Labels: bug

#1237 Supress a coverity false positive
  src/OVAL/probes/independent/textfilecontent54.c
Labels: enhancement

#1241 Removed redundant free.
  swig/src/openscap.i
Labels: bugfix

#1240 Fixed memory leaks in a test.
  tests/API/probes/oval_fts_list.c
Labels: bug

#1244 Fixed a bug with sudo as the first argument.
  utils/oscap-ssh
Labels: bug

#1247 Update man page
  utils/oscap.8
Labels: docs

#1248 Update man page (maint-1.3)
  utils/oscap.8
Labels: docs

#1239 Fixed memory errors in tests.
  tests/API/CPE/lang/test_api_cpe_lang.c
  tests/oscap_string/test_oscap_string.c
Labels: bug

#1249 Ensure there are no unresolved symbols in libopenscap_sce.so
  src/SCE/CMakeLists.txt
Labels: bugfix

#1254 Make sure that the manual HTML is built and distributed.
  Makefile.am
Labels: bugfix
