Repository OpenSCAP/openscap, pull requests merged in 2018-11, with the labels that each got.

#1268 Fix trailing whitespace in Ansible Playbooks
  src/XCCDF_POLICY/xccdf_policy_remediate.c
Labels: enhancement, help wanted

#1279 Increased flexibility of the Python remediation script runner.
  configure.ac
  m4/python.m4
  src/XCCDF_POLICY/xccdf_policy_remediate.c
  tests/API/XCCDF/unittests/test_remediate_python.xccdf.xml
  tests/API/XCCDF/unittests/test_remediate_python_subs.xccdf.xml
Labels: bugfix

#1265 Change test_sysctl_probe_all to succeed for non-root users
  tests/probes/sysctl/test_sysctl_probe_all.sh
Labels: bugfix

#1283 Expand the sysctl test blacklist so it passes.
  tests/probes/sysctl/test_sysctl_probe_all.sh
Labels: test

#1277 fix pull request gating on Python3-only systems
  tests/nist/nist_test.sh
  tests/test_common.sh.in
Labels: bugfix

#1274 Prevent duplicate variables in Ansible Playbooks
  src/XCCDF_POLICY/xccdf_policy_remediate.c
Labels: bugfix, enhancement
