Repository OpenSCAP/openscap, pull requests merged in 2018-06, with the labels that each got.

#1049 Add gcc-c++ to dependencies
  README.md
Labels: docs

#1052 The probes compile options all depend on ENABLE_PROBES
  CMakeLists.txt
Labels: bugfix

#1038 Update release tools to work in master branch
  release_tools/release.sh
  release_tools/up_to_compliance_check.sh
  release_tools/versions.sh
Labels: BLOCKER

#1047 Include an example how to apply generated playbook on localhost
  src/XCCDF_POLICY/xccdf_policy_remediate.c
Labels: docs, enhancement

#1063 Pkgconfig only non windows
  .gitignore
  CMakeLists.txt
Labels: enhancement

#1046 Tests fixes
  .travis.yml
  tests/API/OVAL/unittests/test_object_component_type.sh
  tests/API/XCCDF/unittests/test_xccdf_transformation.sh
  tests/probes/iflisteners/test_probes_iflisteners.sh
  tests/probes/maskattr/test_object_entity_mask.sh
  tests/probes/maskattr/test_object_entity_mask_oval_5_9.sh
  tests/probes/maskattr/test_object_entity_nomask.sh
  tests/probes/rpmverify/test_not_equals_operation.sh
  tests/probes/sysctl/test_sysctl_probe.sh
  tests/probes/sysctl/test_sysctl_probe_all.sh
Labels: enhancement, test

#1071 Config h tests
  tests/API/CVE/test_api_cve.c
  tests/API/CVRF/test_api_cvrf.c
  tests/API/OVAL/schema_version/test_schema_version.c
  tests/API/XCCDF/unittests/test_oscap_common.c
  tests/API/XCCDF/unittests/test_xccdf_overrides.c
  tests/API/XCCDF/unittests/test_xccdf_shall_pass.c
  tests/API/XCCDF/unittests/unit_helper.c
  tests/bz2/test_bz2_memory_source.c
  tests/sources/all.sh
Labels: enhancement, test

#1072 Minor fixes to avoid linker errors when built with disabled probes
  tests/API/CMakeLists.txt
  utils/oscap-oval.c
  utils/oscap-tool.h
  utils/oscap-xccdf.c
  utils/oscap.c
Labels: bugfix

#1074 Update release tools README
  release_tools/README.adoc
Labels: docs

#1078 Fix failing tests if CMake Build Type is release
  tests/API/SEAP/test_api_seap_spb.c
  tests/API/XCCDF/unittests/test_oscap_common.c
  tests/API/XCCDF/unittests/test_xccdf_overrides.c
  tests/API/XCCDF/unittests/test_xccdf_shall_pass.c
  tests/CMakeLists.txt
  tests/assume.h
  tests/bz2/test_bz2_memory_source.c
  tests/oscap_assert.h
  tests/probes/sysinfo/test_probes_sysinfo.c
Labels: test

#1065 Add a guide for writing and running tests
  README.md
  docs/contribute/contribute.adoc
  docs/contribute/testing.adoc
  docs/contribute/versioning.adoc
  tests/test_common.sh.in
Labels: docs, enhancement, test

#1081 Show the test system in HTML report
  xsl/xccdf-report-impl.xsl
Labels: enhancement

#1055 Warn about non-registered check systems
  src/XCCDF_POLICY/xccdf_policy.c
  tests/API/XCCDF/parser/Makefile.am
  tests/API/XCCDF/parser/test_extensions.sh
  tests/API/XCCDF/parser/test_known_extensions.xml
  tests/API/XCCDF/parser/test_malformed_extensions.xml
  tests/API/XCCDF/parser/test_proprietary_extensions.xml
Labels: enhancement

#1084 Set RPATH on by default for OSX
  CMakeLists.txt
Labels: bugfix

#1089 CMake related update of testing guide in the master branch
  docs/contribute/testing.adoc
  tests/sce/test_sce_streams_fill.sh
  tests/test_common.sh.in
Labels: docs
