Repository OpenSCAP/openscap, pull requests merged in 2020-09, with the labels that each got.

#1584 Fix realloc calls to account for a possible NULL result
  src/OVAL/oval_probe_ext.c
  src/OVAL/oval_probe_handler.c
  src/OVAL/probes/SEAP/generic/bitmap.c
  src/OVAL/probes/SEAP/generic/spb.c
  src/OVAL/probes/SEAP/generic/strbuf.c
  src/OVAL/probes/SEAP/seap-message.c
  src/OVAL/probes/SEAP/seap-packet.c
  src/OVAL/probes/SEAP/sexp-manip.c
  src/OVAL/probes/fsdev.c
  src/OVAL/probes/independent/environmentvariable58_probe.c
  src/OVAL/probes/independent/textfilecontent54_probe.c
  src/OVAL/probes/probe/icache.c
  src/OVAL/probes/probe/ncache.c
  src/OVAL/probes/probe/probe_main.c
  src/OVAL/probes/unix/fileextendedattribute_probe.c
  src/OVAL/probes/unix/linux/partition_probe.c
  src/OVAL/probes/unix/linux/rpminfo_probe.c
  src/OVAL/probes/unix/process58_probe.c
  src/OVAL/probes/unix/xinetd_probe.c
  src/SCE/sce_engine.c
  src/XCCDF/xccdf_session.c
  src/XCCDF_POLICY/xccdf_policy_remediate.c
  src/common/oscap_buffer.c
Labels: memory

#1594 Fix memory leak
  src/OVAL/probes/probe-api.c
Labels: memory

#1602 Fix link to compilation instructions
  docs/manual/manual.adoc
Labels: docs

#1609 Fix export of Profile platform to DOM
  src/XCCDF/profile.c
  tests/API/XCCDF/unittests/CMakeLists.txt
  tests/API/XCCDF/unittests/test_xccdf_resolve_profile_platform.sh
  tests/API/XCCDF/unittests/test_xccdf_resolve_profile_platform.xccdf.xml
Labels: bugfix
