Repository OpenSCAP/openscap, pull requests merged in 2021-01, with the labels that each got.

#1669 Fix multiple segfaults and broken test in --stig-viewer feature
  src/XCCDF/result.c
  src/XCCDF/xccdf_session.c
  tests/API/XCCDF/unittests/test_single_rule.xccdf.xml
  tests/API/XCCDF/unittests/test_single_rule_stigw.sh
Labels: bugfix

#1673 File probe behaviour fix
  src/OVAL/probes/oval_fts.c
  src/OVAL/probes/oval_fts.h
  tests/probes/file/CMakeLists.txt
  tests/probes/file/test_probes_file_behaviour.sh
  tests/probes/file/test_probes_file_behaviour.xml
Labels: bugfix, certification blocker

#1667 Add behaviour test for unix/file probe
  tests/probes/file/CMakeLists.txt
  tests/probes/file/test_probes_file_behaviour.sh
  tests/probes/file/test_probes_file_behaviour.xml
Labels: certification blocker

#1675 Fix OVAL enumerations
  src/OVAL/oval_enumerations.c
  src/OVAL/oval_object.c
  src/OVAL/oval_state.c
  src/OVAL/oval_test.c
  src/OVAL/public/oval_types.h
  tests/API/OVAL/unittests/test_skip_valid.sh
  tests/API/OVAL/unittests/test_xmlns_missing.sh
  tests/curl/test_curl_encoding.sh
Labels: certification blocker
